### ISSUE TITLE
关于文章idea想请教几个问题

### ISSUE THREAD

**Issue by Neronjust2017** [Longzhong-Lin/EDA#2]
大佬您好，
本人在业界从事轨迹预测方面的工作，读了您的文章之后有几个问题想请教一下，望不吝赐教。
1. 文章中提到使用BCE loss 代替CE loss (被广泛用在之前的一些工作中)，只是为了适配distinct anchor的mask方式吗？anchor分类任务是否用CE loss更加合适？
2. 在多层evolving anchor 过程中会出现anchor clustring的现象，基于此提出了distinct anchor (使用NMS来实现) 的设计，使得预测轨迹的模态更加分散，但是在某些场景（如目标车辆在大直道上直行等）中真实的模态分布可能比较聚集，distinct anchor的引入是否会适得其反？

**Comment by Longzhong-Lin** [comment]
你好，
1. bce loss建模多个二分类任务，ce loss建模一个多分类任务，bce loss可以用于可变个数的打分对象，同时在我们的实验中bce loss与ce loss的性能相当。
2. distinct anchor的引入，是为了缓解由预测聚集带来的分类歧义性问题，你可以尝试更灵活的去歧义性策略，来实现回归精度和分类精度的tradeoff。
